### ISSUE TITLE
Regional subdivisions in the global section

### ISSUE THREAD

**Issue by EnzoAndree** [rtcovidlive/rtlive-global#5]
Hello!

Good job showing the global data available at https://rtlive.de/global.html

I wonder if you will add the supported regions for each country on that website.

Best regards,
Enzo.

**Comment by AlexAndorra** [comment]
Hi Enzo,
Thanks for the feedback. Adding regions for each country would be ideal but that often requires at least some knowledge of the country and data that we don't always have (especially since some countries only release data in the native language).

As a result, we encourage people with domain knowledge to open pull requests to add new regions 🥳 Michael and Laura worked on German States, I worked on French regions, and there is [currently a PR to include Italian regions](https://github.com/rtcovidlive/rtlive-global/pull/4) -- you can take a look and we'll welcome any PR if you feel like it!

**Comment by michaelosthege** [comment]
I'm closing this issue, because the procedure was explained above.
